let name = prompt("Quel est votre nom?", "Jean")
alert("Vous avez entré: " + name)
let age = prompt("Quel est votre âge?", "30 ans")
alert("Vous avez entré: " + age)
let city = prompt("Où habitez-vous?", "Paris")
alert("Vous avez entré: " + city)